---
name: Setup Environment
author: CISA Development Team
branding:
  icon: globe
  color: purple
description: Setup a shared GitHub Actions workflow environment.
outputs:
  packer-version:
    description: The version of Packer to use.
  shfmt-version:
    description: The version of shfmt to use.
  terraform-version:
    description: The version of Terraform to use.
  terraform-docs-version:
    description: The version of terraform-docs to use.
runs:
  using: 'docker'
  image: 'Dockerfile'
